### ISSUE TITLE
Task 1 (Git)

### ISSUE THREAD

**Issue by ala-n** [ktolkun/Exadel#1]
Task 1 APPROVED.

**Comment by ktalkun** [comment]
Why? Can you clerify the reasons?
Because when my previous teacher said me, that I could to change group she mentioned, that I should pull first task until 16.02 and send github link to Zhanna Vitalevna. And I have done it. You can see date of latest commit in repo task1.

**Comment by ala-n** [comment]
Why, what?
That "issue" item just marker about the task status.
First task (Git) can only be APPROVED or DECLINED. All the rest will have a score up to 10.
Your work where approved without any problems.

**Comment by ktalkun** [comment]
Thanks.
