### ISSUE TITLE
Task 2 (Mockups)

### ISSUE THREAD

**Issue by ala-n** [ktolkun/Exadel#2]
[-] Filters for date and author are missed

All else looks good enough for me. 
[+] Nice prototype! and additional (+) for video demo.
Current mark is **9**

**Comment by ktalkun** [comment]
1. Added filters for date and author;
2. Added popup error windows;
3. Added popup window for deleting posts;
4. Create windows graph (visualization connections between different windows);
5. Added page to display the absence of posts after filtering;
6. Added description functions of button near them.

Check please.

**Comment by ala-n** [comment]
Will do it soon. Thank you!

**Comment by ala-n** [comment]
**10** for Task #2 thanks!
